version: "3.9"

services:
  backend:
    container_name: fastapi-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env